### ISSUE TITLE
Code Review Checklist 

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#286]
https://github.com/twindle-co/twindle/blob/main/docs/CODE-REVIEW-CHECKLIST.MD

Fill which ever you are suggesting to others

@arthurbuhl

**Comment by tusharkandpal** [comment]
Sure!! 🙂

**Comment by proful** [comment]
Please consolidate your comments into this.

No need to format.

No need for approval.

Please keep adding to one file.

**Comment by arthurbuhl** [comment]
### Initial CR Checklist

- For your first PR, please use all lower case for the file name.
- Please use `firstname.md` as file name. Replace `firstname` with your actual first name.
- In case there is already a file with same name, then use `firstname_lastname.md`.
- Using `.md` file extension is a must.
- Please add some basic bio about yourself in the first PR.
- For the second PR, you can update the same file and add more details.

**Comment by proful** [comment]
This is great can you please raise a PR?

**Comment by arthurbuhl** [comment]
Sure. I am on it.

**Comment by proful** [comment]
Let this issue be open always.

It is to continuously improve this doc as we discover more and more issues.

@EYRAM565 make sure you put @arthurbuhl as mandatory approval for any changes to this document

**Comment by EYRAM565** [comment]
ok.

**Comment by pranavgoel29** [comment]
- [x]  Approve PR carefully as they may not show any merge conflict but still there can be some error.

- [x] Check for repeated names too as I can see in some PR the same names are getting repeated 1-2 times

**Comment by pranavgoel29** [comment]
Should we pin this issue so it become more visible and they can add more point to check.

**Comment by pranavgoel29** [comment]
> - [x]  Approve PR carefully as they may not show any merge conflict but still there can be some error.
> 
> - [x] Check for repeated names too in `TEAM.md` as sometimes the same names are getting repeated 1-2 times

Should I add these through a PR ?

**Comment by proful** [comment]
@pranavgoel29 yes of course

**Comment by sarathkumar6** [comment]
- [ ] Offer any suggestions to improve the code in constructive manner

**Comment by shekhar10feb** [comment]
Can we add 3rd PR in Initial CR Checklist??

**Comment by tusharkandpal** [comment]
1. See 'file changed' section to review the summed up code. (Don't go into individual commits)

2. You can comment on a specific line/part of the code which needs improvement by selecting it.

**Comment by johnjacobkenny** [comment]
3. Just to add, you can select a range of lines by clicking and dragging

**Comment by madhusudanbabar** [comment]
also see if there's any new file added to the root of the repo by checking their branch, as it doesn't comes to notice easily from `files changed` tab
