### ISSUE TITLE
Enhancing the twindle-web Landing page

### ISSUE THREAD

**Issue by Akshay2996** [twindle-co/twindle#778]
**We are going make twindle-web look more exciting & user friendly using just Html, CSS & a little bit of JavaScript**

- Right now our initial design looks like this:

![image](https://user-images.githubusercontent.com/37118877/98902415-b6e79480-24db-11eb-9014-f2150250b854.png)
![image](https://user-images.githubusercontent.com/37118877/98902426-b9e28500-24db-11eb-9722-989d051c76c4.png)
![image](https://user-images.githubusercontent.com/37118877/98902430-bcdd7580-24db-11eb-9f72-cae094f48ab2.png)

- **We are taking inspiration from [Notion](https://www.notion.so/) website. Do check it out**

### Tasks

- [x] Make the background look minimal & cool like **[Notion](https://www.notion.so/)**. Use this site as a reference for background: **[HappyHues](https://www.happyhues.co/)**

- [x] Make the footer's background transparent

- [x] Make use of CSS variables in the :root pseudo class for globally assigning properties in the CSS

**PS: If you want to add anything feel free to mention in this issue. When we contribute together we make a great Product**

**Edit: Now our site look like this totally different from the initial design:**

![image](https://user-images.githubusercontent.com/37118877/101273098-9f3cbc80-37b8-11eb-809b-a963a44ded2a.png)
![image](https://user-images.githubusercontent.com/37118877/101273106-aa8fe800-37b8-11eb-8694-e81057994db8.png)
![image](https://user-images.githubusercontent.com/37118877/101273109-ad8ad880-37b8-11eb-9339-8996282de5c3.png)
![image](https://user-images.githubusercontent.com/37118877/101273112-b11e5f80-37b8-11eb-8a07-530290d7be82.png)

**Comment by johnjacobkenny** [comment]
I can give this a try if I can have a copy of our Figma design by Joel. Could someone point me in the right direction if that is the way we want to take this?

**Comment by frankiefab100** [comment]
The design looks good. Is this the one we are going to implement or is there any other?

**Comment by Akshay2996** [comment]
@frankiefab100 We are making some modifications in the design & making it better If you feel like contributing contact me, @UnevenCoder or @vijaya-bhaskar for more information.

Just follow this issue for the same too.

**Comment by PuruVJ** [comment]
One recommendation from my side. I've worked with CSS variables theming, and ultimately, we're gonna introduce that sometime, so my recommendation is to add the CSS variables to the `body` element, with classes like light, dark.

Demo: My site https://puruvj.dev/hello Click on the theming button on top right to see the effect

Source: https://github.com/PuruVJ/puruvjdev2/blob/main/static/css/themes.css

**Comment by Akshay2996** [comment]
### ToDo Tasks

**Priority given to the Task in the Descending order**

For now, We need to focus on these tasks & along the way we can update the tasks accordingly 

- [ ] Testimonials - (Ameen & Titi)
- [ ] Illustrations needed - (Everybody)
- [ ] Email Signup goes to Excel - (Saurabh)
- [ ] Fonts to be adjusted to be uniform - (Joel, Titi) {CSS Variables}
- [ ] Better footer section - (Vijaya & Akshay)
- [ ] Responsive design (Mobile)
- [ ] Team Page (Separate than landing page) - (Ameen & Akshay)

For Illustrations see these sites:
- [Undraw](https://undraw.co/)
- [FreePik](https://www.freepik.com/)
- [ls.graphics](https://www.ls.graphics/free-mockups)
- [Lotte Files](https://lottiefiles.com/)

**PS:** For reference see the illustration [Animated GIF](https://lottiefiles.com/38793-remote-work)

**Comment by Akshay2996** [comment]
### Important for Everyone

- Make use of **Flex** in the sections.
- Use **rem** unit in fonts, margin, padding & avoid using pixel (px) in it.
- Use CSS variables to assign a value in the :root selector to avoid repetition.

**Comment by PuruVJ** [comment]
Scrapping Twindle Web for now
